AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application. 
  This template creates Python Flask Web Application on Amazon Linux 2023 
  AMI (ami-0715c1897453cabd1) EC2 Instance with custom security group 
  allowing http connections on port 80 and SSH connection on port 22. 
  Roman Numerals Converter Application is downloaded from Github 
  repository, then installed on Flask.

Parameters:
  MyKeyPair:
    Description: Choose a key pair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyWebServerSecGr:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP for Flask Web Server and SSH for secure connection"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair
      SecurityGroupIds:
        - !Ref MyWebServerSecGr
      Tags:
        - Key: Name
          Value: !Sub "Web Server Host of ${AWS::StackName}"
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y python3 python3-pip
        pip3 install flask
        yum install -y git
        git clone https://github.com/Yunus-Altay/Project-102-Roman-Numerals-Converter.git
        cd ./Project-102-Roman-Numerals-Converter
        python3 app.py

Outputs:
  WebSiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName
    Description: Roman Numerals Converter Application URL
